// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var $$String = require("bs-platform/lib/js/string.js");

console.log($$String.concat("&", List.map((function (pet) {
                return pet.name;
              }), /* :: */[
              {
                name: "bob"
              },
              /* :: */[
                {
                  name: "bob2"
                },
                /* [] */0
              ]
            ])));

function name(param) {
  return param.name;
}

var pets = /* :: */[
  {
    name: "bob"
  },
  /* :: */[
    {
      name: "bob2"
    },
    /* [] */0
  ]
];

console.log($$String.concat("&", List.map(name, pets)));

console.log(pets);

var petsArray = [
  {
    name: "bob"
  },
  {
    name: "bob2"
  }
];

console.log(petsArray);

console.log($$Array.map((function (pet) {
            return pet.name;
          }), petsArray));

exports.name = name;
exports.pets = pets;
exports.petsArray = petsArray;
/*  Not a pure module */
