// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

function toColor(param) {
  return param[0];
}

var Covering = {
  toColor: toColor
};

function toCovering(param) {
  if (param) {
    return param[0];
  }
  
}

var Species = {
  toCovering: toCovering
};

function toSpecies(param) {
  if (param) {
    return param[0];
  }
  
}

var Thing = {
  toSpecies: toSpecies
};

var toto = /* Animal */[/* Dog */[/* Fur */Block.__(0, ["black"])]];

var totoFurColor = Belt_Option.map(Belt_Option.flatMap(toSpecies(toto), toCovering), toColor);

console.log(totoFurColor);

var nemo = /* Animal */[/* Fish */0];

var nemoFurColor = Belt_Option.map(Belt_Option.flatMap(toSpecies(nemo), toCovering), toColor);

console.log(nemoFurColor);

var $less$$great = Belt_Option.map;

var $great$great$eq = Belt_Option.flatMap;

exports.$less$$great = $less$$great;
exports.$great$great$eq = $great$great$eq;
exports.Covering = Covering;
exports.Species = Species;
exports.Thing = Thing;
exports.toto = toto;
exports.totoFurColor = totoFurColor;
exports.nemo = nemo;
exports.nemoFurColor = nemoFurColor;
/* totoFurColor Not a pure module */
