// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

var match = {
  orThis: "Horray!"
};

var result;

if (match !== undefined) {
  var match$1 = match.orThis;
  result = match$1 !== undefined ? match$1 + " it exists!" : undefined;
} else {
  result = undefined;
}

var match$2 = {
  orThis: undefined
};

var resultNone;

if (match$2 !== undefined) {
  var match$3 = match$2.orThis;
  resultNone = match$3 !== undefined ? match$3 + " it exists!" : undefined;
} else {
  resultNone = undefined;
}

console.log(result);

console.log(resultNone);

var resultWithBelt = Belt_Option.map(Belt_Option.flatMap({
          orThis: "Horray!"
        }, (function (x) {
            return x.orThis;
          })), (function (x) {
        return x + " it exists!";
      }));

console.log("resultWithBelt", resultWithBelt);

var everythingExists = {
  doesThisExist: {
    orThis: "Horray!"
  }
};

var everythingExistsNone = {
  doesThisExist: {
    orThis: undefined
  }
};

var doesntExist = {
  doesThisExist: undefined
};

exports.everythingExists = everythingExists;
exports.everythingExistsNone = everythingExistsNone;
exports.doesntExist = doesntExist;
exports.result = result;
exports.resultNone = resultNone;
exports.resultWithBelt = resultWithBelt;
/*  Not a pure module */
